### ISSUE TITLE
Endpoints that vary only by wildcard presence break each other

### ISSUE THREAD

**Issue by jkyoutsey** [lbdorrou/ngx-mastermock#1]
`/part1/${wildcard1}/part2/${wildcard2}/part3` will work fine.  But if you try to register another endpoint of `/part1/part2/${wildcard2}/part3` the second handler will never get called.

Removing wildcards and doing direct matches works correctly.  So, this can be worked around with a static path.  Any instance of a wildcard in the second one will break.

**Comment by lbdorrou** [comment]
fixed in beta.3
